export const itensPadrao = {
mercearia: [
    { descricao: "ACUCAR CRISTAL", unidade: "FRD" },
    { descricao: "ACUCAR MASCAVO", unidade: "FRD" },
    { descricao: "AMACIANTE DE CARNE 1,1KG", unidade: "PCT" },
    { descricao: "ARROZ 5KG", unidade: "PCT" },
    { descricao: "AZEITE DE OLIVA 500ML", unidade: "UND" },
    { descricao: "AZEITE EXTRA VIRGEM 5L", unidade: "UND" },
    { descricao: "AZEITONA PRETA", unidade: "BLD" },
    { descricao: "BIS CHOCOLATE", unidade: "PCT" },
    { descricao: "BISNAGA CHOC/BRANCO 1,01KG", unidade: "CX" },
    { descricao: "BISNAGA CHOC/LEITE 1,01KG", unidade: "CX" },
    { descricao: "BISNAGA DE DOCE DE LEITE 1,01KG", unidade: "UND" },
    { descricao: "BOMBOM GAROTO", unidade: "PCT" },
    { descricao: "CAFE", unidade: "PCT" },
    { descricao: "CALDO DE GALINHA", unidade: "PCT" },
    { descricao: "CHAMPIGNON", unidade: "BLD" },
    { descricao: "CHOC. GRANULADO", unidade: "PCT" },
    { descricao: "CREME CULINÁRIO", unidade: "CX" },
    { descricao: "ERVILHA", unidade: "UND" },
    { descricao: "FARINHA", unidade: "PCT" },
    { descricao: "FARINHA DE TRIGO SC 25 KG", unidade: "PCT" },
    { descricao: "FEIJÃO BRANCO", unidade: "KG" },
    { descricao: "FEIJÃO CARIOCA", unidade: "KG" },
    { descricao: "FEIJÃO PRETO", unidade: "KG" },
    { descricao: "FOSFORO", unidade: "UND" },
    { descricao: "FUBA DE MILHO", unidade: "FRD" },
    { descricao: "LEITE CONDENSADO 395G", unidade: "UND" },
    { descricao: "LEITE LIQUIDO 1L", unidade: "UND" },
    { descricao: "MARGARINA", unidade: "BLD" },
    { descricao: "MM's", unidade: "PCT" },
    { descricao: "MILHO VERDE", unidade: "UND" },
    { descricao: "MOLHO BARBECUE", unidade: "UND" },
    { descricao: "MOLHO P/ PIZZA", unidade: "CX" },
    { descricao: "MOLHO SHOYU", unidade: "UND" },
    { descricao: "OLEO SOJA 900ML", unidade: "UND" },
    { descricao: "OREGANO", unidade: "PCT" },
    { descricao: "OVOS", unidade: "CRT" },
    { descricao: "PIMENTA BIQUINHO BALDE", unidade: "UND" },
    { descricao: "PIMENTA TABASCO 60ML", unidade: "UND" },
    { descricao: "SAL 1KG", unidade: "FRD" },
    { descricao: "TOMATE SECO BALDE", unidade: "UND" },
    { descricao: "VINAGRE BALSAMICO 500ML", unidade: "UND" }
],
  frios: [
    { descricao: "BACON CUBOS", unidade: "KG" },
    { descricao: "BISTECA", unidade: "KG" },
    { descricao: "CARNE C/ OSSO", unidade: "KG" },
    { descricao: "CARNE NA ROLA", unidade: "KG" },
      { descricao: "CARNE MOÍDA", unidade: "KG" },
    { descricao: "CARNE P/ BIFE", unidade: "KG" },
    { descricao: "CARNE P/ MARIA ISABEL", unidade: "KG" },
    { descricao: "CHEDDAR 1,01KG", unidade: "UND" },
    { descricao: "COXA E SOBRE COXA", unidade: "KG" },
    { descricao: "COSTELA BOVINA", unidade: "KG" },
    { descricao: "COSTELA SUÍNA", unidade: "KG" },
    { descricao: "CREAM CHEESE", unidade: "CX" },
    { descricao: "FRANGO INTEIRO", unidade: "UND" },
    { descricao: "LOMBO CANADENSE", unidade: "UN" },
    { descricao: "PEITO DE FRANGO", unidade: "CX" },
    { descricao: "PEITO DE PERU", unidade: "UN" },
    { descricao: "PONTAS DE CALABRESA", unidade: "KG" },
    { descricao: "PRESUNTO", unidade: "UND" },
    { descricao: "QUEIJO COALHO", unidade: "BARRA" },
    { descricao: "QUEIJO DO REINO", unidade: "BARRA" },
    { descricao: "QUEIJO GORGONZOLA", unidade: "BARRA" },
    { descricao: "QUEIJO MUSSARELA", unidade: "BARRA" },
    { descricao: "QUEIJO PARMESÃO", unidade: "BARRA" },
    { descricao: "QUEIJO PROVOLONE", unidade: "BARRA" },
    { descricao: "REQUEIJÃO CATUPIRY 1,5KG", unidade: "CX" }
],
  bebidas: [
    { descricao: "ÁGUA DE COCO 300ML", unidade: "FRD" },
    { descricao: "ÁGUA MINERAL C/ GÁS - 500ML", unidade: "FRD" },
    { descricao: "ÁGUA MINERAL S/ GÁS - 500ML", unidade: "FRD" },
    { descricao: "CAJUÍNA 500ML", unidade: "FRD" },
    { descricao: "COCA COLA 1L", unidade: "FRD" },
    { descricao: "COCA COLA 2L", unidade: "FRD" },
    { descricao: "COCA COLA 600ML", unidade: "FRD" },
    { descricao: "COCA COLA LATA 350ML", unidade: "FRD" },
    { descricao: "COCA COLA ZERO 1L", unidade: "FRD" },
    { descricao: "COCA COLA ZERO 2L", unidade: "FRD" },
    { descricao: "COCA COLA ZERO 600ML", unidade: "FRD" },
    { descricao: "COCA COLA ZERO LATA 350ML", unidade: "FRD" },
    { descricao: "FANTA LARANJA LATA 350ML", unidade: "FRD" },
    { descricao: "FANTA UVA LATA 350ML", unidade: "FRD" },
    { descricao: "GUARANÁ 1L", unidade: "FRD" },
    { descricao: "GUARANÁ 2L", unidade: "FRD" },
    { descricao: "GUARANÁ 600ML", unidade: "FRD" },
    { descricao: "GUARANÁ JESUS LATA 350ML", unidade: "FRD" },
    { descricao: "GUARANÁ LATA 350ML", unidade: "FRD" },
    { descricao: "GUARANÁ LATA ZERO 350ML", unidade: "FRD" },
    { descricao: "H2O LIMÃO FRD", unidade: "FRD" },
    { descricao: "H2O LIMONETO", unidade: "FRD" },
    { descricao: "SCHEWEPPS LATA 350ML", unidade: "FRD" },
    { descricao: "SODA LIMONADA LATA 350ML", unidade: "FRD" }
  ],
  hortifruti: [
    { descricao: "ABACAXI", unidade: "KG" },
    { descricao: "ACAFRAO", unidade: "KG" },
    { descricao: "ALHO", unidade: "KG" },
    { descricao: "ALHO PORO", unidade: "KG" },
    { descricao: "BANANA PRATA", unidade: "KG" },
    { descricao: "BERINJELA", unidade: "KG" },
    { descricao: "CEBOLA BRANCA", unidade: "KG" },
    { descricao: "CEBOLA ROXA", unidade: "KG" },
    { descricao: "CEBOLINHA", unidade: "UND" },
    { descricao: "CHEIRO VERDE", unidade: "UND" },
    { descricao: "COENTRO", unidade: "UND" },
    { descricao: "LARANJA PERA", unidade: "KG" },
    { descricao: "LIMAO", unidade: "KG" },
    { descricao: "MACA", unidade: "KG" },
    { descricao: "MACAXEIRA", unidade: "KG" },
    { descricao: "MANJERICAO", unidade: "UND" },
    { descricao: "PIMENTAO VERDE", unidade: "KG" },
    { descricao: "PIMENTINHA", unidade: "KG" },
    { descricao: "RUCULA", unidade: "UND" },
    { descricao: "SALSINHA", unidade: "UND" },
    { descricao: "TOMATE", unidade: "KG" },
    { descricao: "TOMATE CEREJA BANDEJA", unidade: "UND" }
  ],
  embalagem: [
    { descricao: "CAIXA PIZZA G", unidade: "UND" },
    { descricao: "CAIXA PIZZA M", unidade: "UND" },
    { descricao: "CAIXA PIZZA P", unidade: "UND" },
    { descricao: "CAIXA PIZZA PP", unidade: "UND" },
    { descricao: "CAIXAS - DELICIA PAULISTA", unidade: "UND" },
    { descricao: "ST PIETRO CAIXA G", unidade: "UND" },
    { descricao: "ST PIETRO CAIXA M", unidade: "UND" },
    { descricao: "ST PIETRO CAIXA P", unidade: "UND" }
  ],
  diversos: [
    { descricao: "BOBINA TÉRMICA", unidade: "CX" },
    { descricao: "COPO DESCARTAVEL 180ML", unidade: "PCT" },
    { descricao: "GUARDANAPO", unidade: "CX" },
    { descricao: "LACRE P/ PIZZA", unidade: "UN" },
    { descricao: "MARMITEX/QUENTINHA", unidade: "UN" },
    { descricao: "MESINHAS P/ PIZZA", unidade: "PCT" },
    { descricao: "SACO 1KG", unidade: "PCT" },
    { descricao: "SACO 2KG", unidade: "PCT" },
    { descricao: "SACO P/ TALHER", unidade: "PCT" },
    { descricao: "SACHE KETCHUP", unidade: "CX" },
    { descricao: "SACHE MAIONESE", unidade: "CX" },
    { descricao: "SACHE MOSTARDA", unidade: "CX" }
  ],
  sobras: [
    { descricao: "QUEIJO MUSSARELA G", unidade: "UN" },
    { descricao: "QUEIJO MUSSARELA M", unidade: "UN" },
    { descricao: "QUEIJO MUSSARELA P", unidade: "UN" },
    { descricao: "CARNE DE SOL G", unidade: "UN" },
    { descricao: "CARNE DE SOL M", unidade: "UN" },
    { descricao: "FILÉ MIGNON G", unidade: "UN" },
    { descricao: "FILÉ MIGNON M", unidade: "UN" },
    { descricao: "CALABRESA G", unidade: "UN" },
    { descricao: "CALABRESA M", unidade: "UN" },
    { descricao: "BACON G", unidade: "UN" },
    { descricao: "BACON M", unidade: "UN" },
    { descricao: "FRANGO DESFIADO G", unidade: "UN" },
    { descricao: "FRANGO DESFIADO M", unidade: "UN" },
    { descricao: "PEPERONI G", unidade: "UN" },
    { descricao: "PEPERONI M", unidade: "UN" }
  ]
};




