export const itensPadrao = {
mercearia: [
    { descricao: "AÇUCAR CRISTAL", unidade: "FRD" },
    { descricao: "AÇUCAR MASCAVO", unidade: "FRD" },
    { descricao: "AZEITE DE OLIVA 500ML", unidade: "UND" },
    { descricao: "AZEITE EXTRA VIRGEM 5L", unidade: "UND" },
    { descricao: "AZEITONA PRETA", unidade: "BLD" },
    { descricao: "BIS CHOCOLATE", unidade: "PCT" },
    { descricao: "BISNAGA CHOC/BRANCO 1,01KG", unidade: "CX" },
    { descricao: "BISNAGA CHOC/LEITE 1,01KG", unidade: "CX" },
    { descricao: "BISNAGA DE DOCE DE LEITE 1,01KG", unidade: "UND" },
    { descricao: "BISNAGA DE GOIABADA", unidade: "UND" },
    { descricao: "CANELA", unidade: "PCT" },
    { descricao: "CAFE", unidade: "PCT" },
    { descricao: "CHAMPIGNON", unidade: "BLD" },
    { descricao: "CHOC. GRANULADO", unidade: "PCT" },
    { descricao: "DETERGENTE 5L", unidade: "UND" },
    { descricao: "CREME CULINÁRIO", unidade: "CX" },
    { descricao: "ERVILHA", unidade: "UND" },
    { descricao: "FARINHA DE TRIGO SC 25 KG", unidade: "PCT" },
    { descricao: "FERMENTO", unidade: "UN" },
    { descricao: "FOSFORO", unidade: "UND" },
    { descricao: "FUBA DE MILHO", unidade: "FRD" },
    { descricao: "ISQUEIRO", unidade: "UND" },
    { descricao: "LEITE CONDENSADO 395G", unidade: "UND" },
    { descricao: "LEITE EM PÓ", unidade: "UND" },
    { descricao: "LEITE LIQUIDO 1L", unidade: "UND" },
    { descricao: "MM's", unidade: "PCT" },
    { descricao: "MILHO VERDE", unidade: "UND" },
    { descricao: "MOLHO BARBECUE", unidade: "UND" },
    { descricao: "MOLHO P/ PIZZA", unidade: "CX" },
    { descricao: "MOLHO SHOYU", unidade: "UND" },
    { descricao: "OLEO SOJA 900ML", unidade: "FRD" },
    { descricao: "OREGANO", unidade: "PCT" },
    { descricao: "OVOS", unidade: "CRT" },
    { descricao: "PIMENTA BIQUINHO", unidade: "BLD" },
    { descricao: "PIMENTA TABASCO 60ML", unidade: "UND" },
    { descricao: "SAL", unidade: "FRD" },
    { descricao: "SONHO DE VALSA", unidade: "PCT" },
    { descricao: "TOMATE SECO", unidade: "BLD" },
    { descricao: "VINAGRE BALSAMICO 500ML", unidade: "UND" }
],
  frios: [
    { descricao: "BACON CUBOS", unidade: "KG" },
    { descricao: "CHEDDAR", unidade: "CX" },
    { descricao: "CREAM CHEESE", unidade: "CX" },
    { descricao: "LOMBO CANADENSE", unidade: "UN" },
    { descricao: "PEITO DE PERU", unidade: "BARRA" },
    { descricao: "PONTAS DE CALABRESA", unidade: "KG" },
    { descricao: "PRESUNTO", unidade: "BARRA" },
    { descricao: "PRESUNTO PHARMA 100G", unidade: "PCT" },
    { descricao: "QUEIJO COALHO", unidade: "BARRA" },
    { descricao: "QUEIJO DO REINO", unidade: "BARRA" },
    { descricao: "QUEIJO GORGONZOLA", unidade: "BARRA" },
    { descricao: "QUEIJO MUSSARELA", unidade: "BARRA" },
    { descricao: "QUEIJO PARMESÃO", unidade: "BARRA" },
    { descricao: "QUEIJO PROVOLONE", unidade: "BARRA" },
    { descricao: "REQUEIJÃO CREMOSO", unidade: "CX" }
],
bebidas: [
  { descricao: "ÁGUA DE COCO 300ML", unidade: "FRD" },
  { descricao: "ÁGUA MINERAL C/ GÁS - 500ML", unidade: "FRD" },
  { descricao: "ÁGUA MINERAL S/ GÁS - 500ML", unidade: "FRD" },
  { descricao: "BRAHMA DUPLO MALTE 600ML", unidade: "FRD" },
  { descricao: "CAJUÍNA 500ML", unidade: "FRD" },
  { descricao: "COCA COLA 1L", unidade: "FRD" },
  { descricao: "COCA COLA 2L", unidade: "FRD" },
  { descricao: "COCA COLA 600ML", unidade: "FRD" },
  { descricao: "COCA COLA LATA 350ML", unidade: "FRD" },
  { descricao: "COCA COLA ZERO 1L", unidade: "FRD" },
  { descricao: "COCA COLA ZERO 2L", unidade: "FRD" },
  { descricao: "COCA COLA ZERO 600ML", unidade: "FRD" },
  { descricao: "COCA COLA ZERO LATA 350ML", unidade: "FRD" },
  { descricao: "FANTA LARANJA LATA 350ML", unidade: "FRD" },
  { descricao: "FANTA UVA LATA 350ML", unidade: "FRD" },
  { descricao: "GUARANÁ 1L", unidade: "FRD" },
  { descricao: "GUARANÁ 2L", unidade: "FRD" },
  { descricao: "GUARANÁ 600ML", unidade: "FRD" },
  { descricao: "GUARANÁ JESUS LATA 350ML", unidade: "FRD" },
  { descricao: "GUARANÁ LATA 350ML", unidade: "FRD" },
  { descricao: "GUARANÁ LATA ZERO 350ML", unidade: "FRD" },
  { descricao: "H2O LIMÃO FRD", unidade: "FRD" },
  { descricao: "H2O LIMONETO", unidade: "FRD" },
  { descricao: "HEINEKEN 600ML", unidade: "FRD" },
  { descricao: "HEINEKEN LONG NECK", unidade: "FRD" },
  { descricao: "IMPERIO LONG NECK", unidade: "FRD" },
  { descricao: "SCHEWEPPS LATA 350ML", unidade: "FRD" },
  { descricao: "SODA LIMONADA LATA 350ML", unidade: "FRD" },
  { descricao: "STELLA 600ML", unidade: "FRD" },
  { descricao: "STELLA LONG NECK", unidade: "FRD" }
],
  hortifruti: [
    { descricao: "ABACAXI", unidade: "KG" },
    { descricao: "ALECRIN", unidade: "KG" },
    { descricao: "ALHO", unidade: "KG" },
    { descricao: "ALHO PORO", unidade: "KG" },
    { descricao: "BANANA", unidade: "KG" },
    { descricao: "BERINJELA", unidade: "KG" },
    { descricao: "CEBOLA BRANCA", unidade: "KG" },
    { descricao: "CEBOLA ROXA", unidade: "KG" },
    { descricao: "CEBOLINHA", unidade: "UND" },
    { descricao: "LIMAO", unidade: "KG" },
    { descricao: "MACA", unidade: "KG" },
    { descricao: "MACAXEIRA", unidade: "KG" },
    { descricao: "MANJERICAO", unidade: "UND" },
    { descricao: "PIMENTAO VERDE", unidade: "KG" },
    { descricao: "PIMENTINHA", unidade: "KG" },
    { descricao: "RUCULA", unidade: "UND" },
    { descricao: "SALSINHA", unidade: "UND" },
    { descricao: "TOMATE", unidade: "KG" },
    { descricao: "TOMATE CEREJA", unidade: "BAND" }
  ],
  embalagem: [
    { descricao: "FORNO CAIXA G", unidade: "UND" },
    { descricao: "FORNO CAIXA M", unidade: "UND" },
    { descricao: "FORNO CAIXA P", unidade: "UND" },
    { descricao: "FORNO CAIXA PP", unidade: "UND" },
    { descricao: "DELICIA PAULISTA", unidade: "PCT" },
    { descricao: "PIETRO CAIXA G", unidade: "UND" },
    { descricao: "PIETRO CAIXA M", unidade: "UND" },
    { descricao: "PIETRO CAIXA P", unidade: "UND" },
    { descricao: "MY PIZZA CAIXA G", unidade: "UND" },
    { descricao: "MY PIZZA CAIXA M", unidade: "UND" },
    { descricao: "MY PIZZA CAIXA P", unidade: "UND" },
    { descricao: "ESFIRA CAIXA G", unidade: "UND" },
    { descricao: "ESFIRA CAIXA M", unidade: "UND" },
    { descricao: "ESFIRA CAIXA P", unidade: "UND" },
  ],
  diversos: [
    { descricao: "BOBINA TÉRMICA", unidade: "CX" },
    { descricao: "BORRIFADOR", unidade: "UND" },
    { descricao: "CADEADO", unidade: "UND" },
    { descricao: "CANETA BIC", unidade: "UND" },
    { descricao: "COPO DESCARTAVEL", unidade: "PCT" },
    { descricao: "FACA", unidade: "UND" },
    { descricao: "GUARDANAPO", unidade: "CX" },
    { descricao: "JARRA", unidade: "UND" },
    { descricao: "KIT DE TALHER", unidade: "PCT" },
    { descricao: "LACRE P/ PIZZA", unidade: "UN" },
    { descricao: "LUVAS PRETAS", unidade: "CX" },
    { descricao: "MESINHAS P/ PIZZA", unidade: "PCT" },
    { descricao: "PLASTICO FILME", unidade: "UND" },
    { descricao: "SACO ADESIVO", unidade: "PCT" },
    { descricao: "SACO P/ MASSA", unidade: "UND" },
    { descricao: "SACO P/ TALHER", unidade: "PCT" },
    { descricao: "SACHE KETCHUP", unidade: "CX" },
    { descricao: "SACHE MAIONESE", unidade: "CX" },
    { descricao: "SACHE MOSTARDA", unidade: "CX" },
    { descricao: "TAÇAS", unidade: "CX" }
  ],
    extras: [
    { descricao: "BOBINA TÉRMICA", unidade: "CX" },
    { descricao: "BORRIFADOR", unidade: "UND" },
    { descricao: "CADEADO", unidade: "UND" },
    { descricao: "CANETA BIC", unidade: "UND" },
    { descricao: "COPO DESCARTAVEL", unidade: "PCT" },
    { descricao: "FACA", unidade: "UND" },
    { descricao: "GUARDANAPO", unidade: "CX" },
    { descricao: "JARRA", unidade: "UND" },
    { descricao: "KIT DE TALHER", unidade: "PCT" },
    { descricao: "LACRE P/ PIZZA", unidade: "UN" },
    { descricao: "LUVAS PRETAS", unidade: "CX" },
    { descricao: "MARMITEX/QUENTINHA", unidade: "UN" },
    { descricao: "MESINHAS P/ PIZZA", unidade: "PCT" },
    { descricao: "PLASTICO FILME", unidade: "UND" },
    { descricao: "SACO 2KG", unidade: "PCT" },
    { descricao: "SACO ADESIVO", unidade: "PCT" },
    { descricao: "SACO P/ MASSA", unidade: "UND" },
    { descricao: "SACO P/ TALHER", unidade: "PCT" },
    { descricao: "SACHE KETCHUP", unidade: "CX" },
    { descricao: "SACHE MAIONESE", unidade: "CX" },
    { descricao: "SACHE MOSTARDA", unidade: "CX" },
    { descricao: "TAÇAS", unidade: "CX" }
  ],
  sobras: [
    { descricao: "QUEIJO MUSSARELA G", unidade: "UN" },
    { descricao: "QUEIJO MUSSARELA M", unidade: "UN" },
    { descricao: "QUEIJO MUSSARELA P", unidade: "UN" },
    { descricao: "CARNE DE SOL G", unidade: "UN" },
    { descricao: "CARNE DE SOL M", unidade: "UN" },
    { descricao: "FILÉ MIGNON G", unidade: "UN" },
    { descricao: "FILÉ MIGNON M", unidade: "UN" },
    { descricao: "CALABRESA G", unidade: "UN" },
    { descricao: "CALABRESA M", unidade: "UN" },
    { descricao: "BACON G", unidade: "UN" },
    { descricao: "BACON M", unidade: "UN" },
    { descricao: "FRANGO DESFIADO G", unidade: "UN" },
    { descricao: "FRANGO DESFIADO M", unidade: "UN" },
    { descricao: "PEPERONI G", unidade: "UN" },
    { descricao: "PEPERONI M", unidade: "UN" }
  ]
};






















